SCREEN_WIDTH = 2880
SCREEN_HEIGHT = 1800
DEFAULT_WIDTH = 2000
DEFAULT_HEIGHT = 1250
DEFAULT_SCR_TOP_OFFSET = 210
DEFAULT_SCR_BOTTOM_OFFSET = 170
FORMATS_TO_COMPRESS = ['bmp', 'jpeg', 'jpg', 'png', 'heif', 'tiff', 'gif', 'webp']
